
- Name: Belgorod
  ip: 192.168.10.1
  username: admin
  password: password1
  tarif_id:
  - 1: shaper_10Mbit
  - 2: shaper_20Mbit
  - 3: shaper_30Mbit

- Name: StOskol
  ip: 192.168.11.1
  username: admin
  password: password2
  tarif_id:
  - 1: shaper_10Mbit
  - 2: shaper_20Mbit
  - 3: shaper_30Mbit

