
Belgorod:
  ip: 192.168.10.1
  username: admin
  password: password1
  BlockListName: BillBlock
  tarif_id:
    1: shaper_10Mbit
    2: shaper_20Mbit
    3: shaper_30Mbit

StOskol:
  ip: 192.168.10.1
  username: admin
  password: password2
  BlockListName: BillBlock
  tarif_id:
    1: shaper_10Mbit
    2: shaper_20Mbit
    3: shaper_30Mbit

